/* SNR-MD1 */

#define BOARD_PID		"SNR-MD1"
#define BOARD_NAME		"SNR-MD1"
#define BOARD_DESC		"SNR-MD1 Wireless Router"
#define BOARD_VENDOR_NAME	"SNR"
#define BOARD_VENDOR_URL	"https://nag.ru/"
#define BOARD_MODEL_URL		"https://wikidevi.wi-cat.ru/NAG_SNR-CPE-MD1"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	90
#define BOARD_GPIO_BTN_RESET	13
#undef  BOARD_GPIO_BTN_WPS	
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI	
#undef  BOARD_GPIO_LED_POWER	
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN	
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	1
#define BOARD_NUM_ANT_5G_RX	1
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
