/* SNR-ME1 */

#define BOARD_PID "SNR-ME1"
#define BOARD_NAME "SNR-ME1"
#define BOARD_DESC "SNR-ME1 Wireless Router"
#define BOARD_VENDOR_NAME "SNR"
#define BOARD_VENDOR_URL"https://nag.ru/"
#define BOARD_MODEL_URL"https://wikidevi.wi-cat.ru/NAG_SNR-CPE-ME1"
#define BOARD_BOOT_TIME 30
#define BOARD_FLASH_TIME 120
#define BOARD_GPIO_BTN_RESET 14
#undef BOARD_GPIO_BTN_WPS 
#undef BOARD_GPIO_LED_ALL
#undef BOARD_GPIO_LED_WIFI
#undef BOARD_GPIO_LED_SW2G 
#undef BOARD_GPIO_LED_SW5G 
#undef BOARD_GPIO_LED_POWER 
#undef BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN	
#define BOARD_GPIO_LED_USB 13
#undef BOARD_GPIO_LED_USB2
#undef BOARD_GPIO_LED_ROUTER
#undef BOARD_GPIO_PWR_USB
#define BOARD_GPIO_PWR_USB 17
#define BOARD_GPIO_PWR_USB_ON 1 /* 1: 5V Power ON, 0: 5V Power OFF */
#define BOARD_HAS_5G_11AC 1
#define BOARD_NUM_ANT_5G_TX 1
#define BOARD_NUM_ANT_5G_RX 1
#define BOARD_NUM_ANT_2G_TX 2
#define BOARD_NUM_ANT_2G_RX 2
#define BOARD_NUM_ETH_LEDS 1
#define BOARD_HAS_EPHY_L1000 1
#define BOARD_HAS_EPHY_W1000 1
#define BOARD_NUM_UPHY_USB3 1
